- hosts: all
  gather_facts: no
  tasks:
    - name: Add docker repo
      copy:
        src: "docker-ce.repo"
        dest: "/etc/yum.repos.d/docker-ce.repo"
        backup: yes
    - name: Remove runc
      yum:
        name: runc
        state: absent
    - name: Install docker-ce
      yum:
        name: docker-ce, docker-ce-cli, containerd.io
        update_cache: yes
        state: present
    - name: Configure Docker mirror
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {"registry-mirrors":["http://f1361db2.m.daocloud.io"]}
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
        state: restarted
        daemon-reload: yes
    - name: Install pip
      yum:
        name: python3-pip
        state: present
    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
    - name: Create docker-compose symlink for root
      file:
        path: "/usr/bin/docker-compose"
        src: "/usr/local/bin/docker-compose"
        state: link
